### ISSUE TITLE
Singleline heredoc causes following lines to be rendered as Strings

### ISSUE THREAD

**Issue by aeschli** [atom/language-shellscript#108]
```sh
#!/bin/bash
sudo tee -a  /etc/environment <<< "http_proxy=\"http://${http_proxy_input}\""
echo "This is not rendered as String"
```

VSCode
![vscode](https://user-images.githubusercontent.com/22315436/36141683-fb2bf994-10a5-11e8-9b74-6c2401fbc087.png)

Notepad++
![notepadplusplus](https://user-images.githubusercontent.com/22315436/36141686-fef11e88-10a5-11e8-9dfc-9c6ccbfdac56.png)

_Copied from original issue: Microsoft/vscode#43567_

**Comment by Arcanemagus** [comment]
This is fixed if you use the new [Tree-sitter](http://tree-sitter.github.io/tree-sitter) parsing system, which is enabled by default in Atom 1.32 Beta. If you're not the beta channel, you can enable it manually by checking the `Use Tree-sitter Parsers` box in the settings view, or wait for Atom 1.32 Stable to be released.

Tree-sitter:
![image](https://user-images.githubusercontent.com/427137/46757760-f2ba2b00-cc7f-11e8-848c-3e4d334548d4.png)

Text-Mate:
![image](https://user-images.githubusercontent.com/427137/46757782-fe0d5680-cc7f-11e8-9e66-2f793fd77bb9.png)

If you are interested in fixing this bug for the TextMate grammar system used in other projects (such as VSCode) we would be happy to accept a PR, however we probably won't prioritize work on these kinds of things ourselves, since Atom is moving away from TextMate for this language.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), I'm closing this issue as it no longer affects Atom.

Thanks for reaching out!
