### ISSUE TITLE
Parameter to script incorrectly scoped to support.function.builtin.shell

### ISSUE THREAD

**Issue by alexr00** [atom/language-shellscript#137]
_From @YuanshengZhao on February 25, 2019 9:30_

Steps to Reproduce:
1. create a shell typed document. ex: `foo.sh`.
2. paste `./a.out test`.

The TextMate grammar is incorrectly categorizing `test` as `support.function.builtin.shell`, even though it is not a function.

![image](https://user-images.githubusercontent.com/37881856/53327484-3cec3200-392b-11e9-8246-69370a2d8f83.png)

_Copied from original issue: Microsoft/vscode#69336_

**Comment by rsese** [comment]
Thanks for the report!

> The TextMate grammar is incorrectly categorizing `test` as `support.function.builtin.shell`, even though it is not a function.

This particular problem doesn't look like an issue with Tree-sitter so we'll go ahead and close as described below.

---

As you may have heard, we are migrating from our old [first-mate grammar engine](https://github.com/atom/first-mate) to the [new Tree-sitter engine](https://blog.github.com/2018-10-31-atoms-new-parsing-system/). This will enable a number of new features, more consistent syntax highlighting, and better performance, among other benefits. In order to free up our limited resources, we have decided to stop maintaining the first-mate grammar when there is a built-in Tree-sitter grammar available. Since this issue applies only to the first-mate grammar, we are going to close it. Please let us know if we have misunderstood the description of the problem.
