### ISSUE TITLE
TextMate grammar handling double quoted value in an unexpected way

### ISSUE THREAD

**Issue by alexr00** [atom/language-shellscript#140]
Originally from @Magicloud [here](https://github.com/Microsoft/vscode/issues/71479)

Sample code
```
someVar="$(someCmd | while read -r aVar; do
  someProc "${aVar}"
done)"
anotherLine
```
After the end quote, tokenization is unexpected.

![image](https://user-images.githubusercontent.com/38270282/56817887-bd091800-6846-11e9-81ec-aa74eb9c0701.png)

**Comment by 50Wliu** [comment]
The provided repro case works in tree-sitter.
![tree-sitter](https://user-images.githubusercontent.com/2766036/56837410-4ec55500-6848-11e9-9bde-f7f9775e17c9.png)

Thanks very much for reaching out!

As you may have heard, we are migrating from our old [first-mate grammar engine](https://github.com/atom/first-mate) to the [new Tree-sitter engine](https://blog.github.com/2018-10-31-atoms-new-parsing-system/). This will enable a number of new features, more consistent syntax highlighting, and better performance, among other benefits. In order to free up our limited resources, we have decided to stop maintaining the first-mate grammar when there is a built-in Tree-sitter grammar available. Since this issue applies only to the first-mate grammar, we are going to close it. Please let us know if we have misunderstood the description of the problem.

Thanks again for your interest in Atom.
