### ISSUE TITLE
bash syntax highlight issue 

### ISSUE THREAD

**Issue by aeschli** [atom/language-shellscript#98]
_From @intijk on January 9, 2018 7:3_

![](https://raw.githubusercontent.com/intijk/refimage/master/bash_syntax.png)

line 247 , issue since `case in` 

And no longer give highlight to `for` `if` after that.

```bash

echo 
if [ "$IS_GITHUB_BUILD" = true ]; then
	echo Github build
	echo Checking / downloading the latest archives
	Build/BatchFiles/Linux/GitDependencies.sh --prompt "$@"
else
	echo Perforce build
	echo Assuming availability of up to date third-party libraries
fi

# Fixes for case sensitive filesystem.
echo Fixing inconsistent case in filenames.
for BASE in Content/Editor/Slate Content/Slate Documentation/Source/Shared/Icons; do
  find $BASE -name "*.PNG" | while read PNG_UPPER; do
    png_lower="$(echo "$PNG_UPPER" | sed 's/.PNG$/.png/')"
    if [ ! -f $png_lower ]; then
      PNG_UPPER=$(basename $PNG_UPPER)
      echo "$png_lower -> $PNG_UPPER"
      # link, and not move, to make it usable with Perforce workspaces
      ln -sf `basename "$PNG_UPPER"` "$png_lower"
    fi
  done
done
```

_Copied from original issue: Microsoft/vscode#41328_

**Comment by aeschli** [comment]
_From @intijk on January 9, 2018 7:3_

Wow, github has same issue.

**Comment by intijk** [comment]
@aeschli Hi could you tell me why vscode issue depend on this atom issue?

**Comment by 50Wliu** [comment]
Thanks very much for reaching out!

As you may have heard, we are migrating from our old [first-mate grammar engine](https://github.com/atom/first-mate) to the [new Tree-sitter engine](https://blog.github.com/2018-10-31-atoms-new-parsing-system/). This will enable a number of new features, more consistent syntax highlighting, and better performance, among other benefits. In order to free up our limited resources, we have decided to stop maintaining the first-mate grammar when there is a built-in Tree-sitter grammar available. Since this issue applies only to the first-mate grammar, we are going to close it. Please let us know if we have misunderstood the description of the problem.

Thanks again for your interest in Atom.

**Comment by 50Wliu** [comment]
@intijk VSCode uses many of Atom's languages for their syntax highlighting.
